// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {websocket} from '../models';
import {http} from '../models';

export function ChatCompletion(arg1:main.ChatRequest):Promise<main.ChatResponse>;

export function CheckOllamaAvailable():Promise<boolean>;

export function DeleteModel(arg1:string):Promise<Record<string, any>>;

export function GetEnvironmentInfo():Promise<Record<string, any>>;

export function GetEnvironmentVariables():Promise<Record<string, any>>;

export function GetIntelOptimizationInfo():Promise<Record<string, any>>;

export function GetOllamaPath():Promise<Record<string, any>>;

export function GetOnlineModels(arg1:number,arg2:number):Promise<Record<string, any>>;

export function GetServiceStatus():Promise<Record<string, any>>;

export function GetStats():Promise<Record<string, any>>;

export function ListModels():Promise<Array<main.ModelInfo>>;

export function PullModel(arg1:string):Promise<Record<string, any>>;

export function SaveEnvironmentVariables(arg1:Record<string, any>):Promise<Record<string, any>>;

export function SearchOnlineModels(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function ShowModel(arg1:string):Promise<Record<string, any>>;

export function StartService():Promise<Record<string, any>>;

export function StopService():Promise<Record<string, any>>;

export function WebSocketChat(arg1:websocket.Conn):Promise<void>;

export function WebSocketHandler(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;
