// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatCompletion(arg1) {
  return window['go']['main']['App']['ChatCompletion'](arg1);
}

export function CheckOllamaAvailable() {
  return window['go']['main']['App']['CheckOllamaAvailable']();
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function GetEnvironmentInfo() {
  return window['go']['main']['App']['GetEnvironmentInfo']();
}

export function GetEnvironmentVariables() {
  return window['go']['main']['App']['GetEnvironmentVariables']();
}

export function GetIntelOptimizationInfo() {
  return window['go']['main']['App']['GetIntelOptimizationInfo']();
}

export function GetOllamaPath() {
  return window['go']['main']['App']['GetOllamaPath']();
}

export function GetOnlineModels(arg1, arg2) {
  return window['go']['main']['App']['GetOnlineModels'](arg1, arg2);
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function PullModel(arg1) {
  return window['go']['main']['App']['PullModel'](arg1);
}

export function SaveEnvironmentVariables(arg1) {
  return window['go']['main']['App']['SaveEnvironmentVariables'](arg1);
}

export function SearchOnlineModels(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchOnlineModels'](arg1, arg2, arg3);
}

export function ShowModel(arg1) {
  return window['go']['main']['App']['ShowModel'](arg1);
}

export function StartService() {
  return window['go']['main']['App']['StartService']();
}

export function StopService() {
  return window['go']['main']['App']['StopService']();
}

export function WebSocketChat(arg1) {
  return window['go']['main']['App']['WebSocketChat'](arg1);
}

export function WebSocketHandler(arg1, arg2) {
  return window['go']['main']['App']['WebSocketHandler'](arg1, arg2);
}
